# Automatically generated by configure
# Configured with: './configure' '--platform=opendingux' '--sound-drivers=sdl'
CC = mipsel-linux-gcc
CXX = mipsel-linux-g++
AS = mipsel-linux-as
STRIP = mipsel-linux-strip
CFLAGS +=  -I/opt/rs97/mipsel-rs97-linux-uclibc/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result
ASFLAGS += 
LDFLAGS += 
LDLIBS += -lSDL -lpthread -lpng  -lm -lz

ARCH = mipsel
PLATFORM = opendingux
SOUND_DRIVERS = sdl
